version: "3.4"

services:
  prod:
    build:
      dockerfile: "docker/prod.dockerfile"
      context: "."
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  dev:
    build:
      dockerfile: "docker/dev.dockerfile"
      context: "."
    ports:
      - "8000:8000"
    volumes:
      - ./:/app